/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.resume.panel;

import com.company.dao.inter.EmploymentHistoryDaoInter;
import com.company.dao.inter.UserDaoInter;
import com.company.entity.EmploymentHistory;
import com.company.main.Context;
import com.company.resume.Config;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author dell
 */
public class EmploymentHistoryPanel extends javax.swing.JPanel {

   

    /**
     * Creates new form EmploymentHistoryPanel
     */
    public EmploymentHistoryPanel() {
        initComponents();

    }
//    
//    public List<EmploymentHistory> fillWindow() {
//        List<EmploymentHistory> list = new ArrayList<>();
//        for (EmploymentHistory empHis : empHistDao.getAllEmploymentHistoryByUserId(Config.loggedInUser.getId())) {
//            CBoxEmpHis.addItem(empHis.getHeader());
//        }
//        return list;
//    }

    public void fillUserComponents() {
        
        String job_name = Config.emHist.getHeader();
        Date start_Date = Config.emHist.getStart_date();
        Date end_Date = Config.emHist.getEnd_date();
        String job_desc = Config.emHist.getJob_description();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String start = sdf.format(start_Date);
        String end = sdf.format(end_Date);
        txtStartDate.setText(start);
        txtEndDate.setText(end);
        txtAreaJobDesc.setText(job_desc);
        txtHeader.setText(job_name);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEmpHis = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        lblEndDate = new javax.swing.JLabel();
        lblJobDesc = new javax.swing.JLabel();
        txtHeader = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaJobDesc = new javax.swing.JTextArea();

        lblHeader.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

        lblStartDate.setText("Start date:");

        txtStartDate.setText("jTextField1");

        txtEndDate.setText("jTextField1");

        lblEndDate.setText("End date: ");

        lblJobDesc.setText("Job Description");

        txtHeader.setText("jTextField1");
        txtHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeaderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmpHisLayout = new javax.swing.GroupLayout(pnlEmpHis);
        pnlEmpHis.setLayout(pnlEmpHisLayout);
        pnlEmpHisLayout.setHorizontalGroup(
            pnlEmpHisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmpHisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(450, 450, 450))
            .addGroup(pnlEmpHisLayout.createSequentialGroup()
                .addGroup(pnlEmpHisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEmpHisLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlEmpHisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlEmpHisLayout.createSequentialGroup()
                                .addComponent(lblStartDate)
                                .addGap(18, 18, 18)
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEmpHisLayout.createSequentialGroup()
                                .addComponent(lblEndDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlEmpHisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblJobDesc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEmpHisLayout.setVerticalGroup(
            pnlEmpHisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpHisLayout.createSequentialGroup()
                .addGroup(pnlEmpHisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEmpHisLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblHeader))
                    .addGroup(pnlEmpHisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEmpHisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStartDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEmpHisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndDate))
                .addGap(27, 27, 27)
                .addComponent(lblJobDesc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtAreaJobDesc.setColumns(20);
        txtAreaJobDesc.setRows(5);
        jScrollPane1.setViewportView(txtAreaJobDesc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEmpHis, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEmpHis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeaderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeaderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblJobDesc;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JPanel pnlEmpHis;
    private javax.swing.JTextArea txtAreaJobDesc;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtHeader;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
}
